version: '3'

services:
  nosql-db:
    image: mongo
    container_name: nosql-db
    ports:
      - 27017:27017
    volumes:
      - ./db/:/data/db

  products:
    build:
      dockerfile: Dockerfile
      context: ./products
    container_name: products
    ports:
      - 8002:8002
    restart: always
    depends_on:
      - nosql-db
    volumes:
      - .:/app
      - /app/products/node_modules

  shopping:
    build:
      dockerfile: Dockerfile
      context: ./shopping
    container_name: shopping
    ports:
      - 8001:8001
    restart: always
    depends_on:
      - nosql-db
    volumes:
      - .:/app
      - /app/shopping/node_modules

  customer:
    build:
      dockerfile: Dockerfile
      context: ./customer
    container_name: customer
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - nosql-db
    volumes:
      - .:/app
      - /app/customer/node_modules

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - customer
      - shopping
      - products
    ports:
      - 80:80